SCR_MissionHeaderCampaign : "{C41618FD18E9D714}Missions/23_Campaign_Arland.conf" {
 World "{D35EDACE18B3F3CD}Worlds/Arland_HQC_PodvalConflict/Arland_HQC_PodvalConflict.ent"
 m_sName "#AR-Campaign_HQC_ScenarioName_Arland"
 m_sDescription "#AR-Campaign_HQC_GamemodeDesc"
 m_sDetails "#AR-Campaign_HQC_Hint_Text"
 m_sIcon "{7D7FBB064F107767}images/middlePlayerImage.edds"
 m_sLoadingScreen "{7D7FBB064F107767}images/middlePlayerImage.edds"
 m_sPreviewImage "{7D7FBB064F107767}images/middlePlayerImage.edds"
 m_bRandomStartingWeather 1
 m_bRandomWeatherChanges 1
 m_bMapMarkerEnableDeleteByAnyone 1
 m_iMapMarkerLimitPerPlayer 15
 m_iControlPointsCap 2
 m_fVictoryTimeout 1500
 m_bCommanderRoleEnabled 1
 m_bEstablishingBasesEnabled 1
 m_bSuppliesAutoRegenerationEnabled 0
}